### PR TITLE
Gzip response support

### LINKED ISSUE #19: Support gzip encoding
In the latest release of Geocodio, he added support for gzip encoding. I tested externally and it is working well. 

The library doesn't currently set the "Accept-Encoding: gzip" header so it works fine. However it seems there should be an option to do so.

Just playing around with it I got it to work. 

First, the header needs to be added to the request. Just one single line added to the request builders.

```java
    public CompletableFuture<GeocodingResponse> geocodeAsync(GeocodingRequest request) {
        var query = initializeRequestQuery();
        query.put("q", request.q());
        query.put("country", request.country());
        query.put("fields", formatFieldsParam(request.fields()));
        query.put("limit", Optional.ofNullable(request.limit()).map(Object::toString).orElse(null));
        query.put("format", request.format());
        query.put("street", request.street());
        query.put("city", request.city());
        query.put("state", request.state());
        query.put("postal_code", request.postalCode());
        var uri = buildURI("geocode", query);
        var httpRequest = HttpRequest.newBuilder()
                .header("Accept-Encoding", "gzip")
                .GET()
                .uri(uri)
                .build();
        return sendAsync(httpRequest, GeocodingResponse.class);
    }
```

Next, the `sendAsync` method needs to handle the decompression in  the `Content-Type` is set. I just quickly got this working so I'm not sure it this is the best way to handle it. 

```java
    private <T> CompletableFuture<T> sendAsync(HttpRequest httpRequest, Class<T> clazz) {
        return httpClient.sendAsync(httpRequest, HttpResponse.BodyHandlers.ofInputStream())
                .thenApply(resp -> {
                    try (InputStream rawStream = resp.body();
                         InputStream stream = "gzip".equals(resp.headers().firstValue("Content-Encoding").orElse(""))
                                 ? new GZIPInputStream(rawStream)
                                 : rawStream) {
                        String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);

                        if (resp.statusCode() != 200)
                            throw new GeocodioStatusCodeException(resp.statusCode(), json);

                        return gson.fromJson(json, clazz);
                    }
                    catch (IOException e) {
                        throw new IllegalStateException("Error reading response", e);
                    }
                });
    }
```

I was able to verify this works using `IntegrationTest`. 

My questions are:

- should the library allow the user to choose whether to request gzip responses or should it just always do it?
- is this a code acceptable?

### PR DESCRIPTION
**Pull request by deansg**
Closes #19 

Add support for requesting API responses to be gzipped.

### CODE REVIEW

File: src/main/java/io/github/deansg/jeocodio/GeocodioClient.java [hunk 1]
```diff
@@ -132,28 +157,57 @@ private String formatFieldsParam(List<String> fields) {
...
+            return json;
+        } catch (IOException e) {
+            throw new RuntimeException(e);
+        }
+    }
+
+    private InputStream getResponseInputStream(HttpResponse<InputStream> resp) throws IOException {
+        var inputStream = resp.body();
+        if (resp.headers().firstValue("Content-Encoding").orElse("").equals("gzip")) {
+            inputStream = new GZIPInputStream(inputStream);
```
Comment (ctmay4) [inline src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:180]: Is this a memory leak? Generally input stream creation needs to be done in a try-with block to handle closing of the streams. My IDE was even complaining about `resp.body()` so I also put that in a try-with resource for my sample. Its possible that is a false positive though.

Comment (deansg) [reply src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:180]: The GZIPInputStream should close the underlying stream, and it is used in a try-with-resources in the calling method. Theoretically if the GZIPInputStream creation itself fails it might somehow cause a leak, but honestly I'm not sure we need to explicitly address that. See for example:
https://stackoverflow.com/questions/53502626/does-java-http-client-handle-compression
If you think we should handle it just in case then I can add another try-catch specifically in this method, and call close on the raw stream.

**Comment by ctmay4** [comment]
Everything looks good, but I have a little concern that a `GZIPInputStream` is not being closed and could leak.

If you look at my sample, I put all the `InputStream` creation in a try-with resource.

```java
    private <T> CompletableFuture<T> sendAsync(HttpRequest httpRequest, Class<T> clazz) {
        return httpClient.sendAsync(httpRequest, HttpResponse.BodyHandlers.ofInputStream())
                .thenApply(resp -> {
                    try (InputStream rawStream = resp.body();
                         InputStream stream = "gzip".equals(resp.headers().firstValue("Content-Encoding").orElse(""))
                                 ? new GZIPInputStream(rawStream)
                                 : rawStream) {
                        String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);

                        if (resp.statusCode() != 200)
                            throw new GeocodioStatusCodeException(resp.statusCode(), json);

                        return gson.fromJson(json, clazz);
                    }
                    catch (IOException e) {
                        throw new IllegalStateException("Error reading response", e);
                    }
                });
    }
```

File: src/main/java/io/github/deansg/jeocodio/GeocodioClient.java (hunk 1 above)
Comment (ctmay4) [reply src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:180]: If you think it is safe, then that's fine. I'm probably overly safe with these types of issues since I've been burned in the past.

File: src/main/java/io/github/deansg/jeocodio/GeocodioClient.java [hunk 2]
```diff
@@ -132,28 +157,57 @@ private String formatFieldsParam(List<String> fields) {
...
 
+    private String readResponse(HttpResponse<InputStream> resp) {
+        try (var inputStream = getResponseInputStream(resp)) {
+            String json = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
+            if (resp.statusCode() != 200) {
+                throw new GeocodioStatusCodeException(resp.statusCode(), json);
+            }
+            return json;
+        } catch (IOException e) {
+            throw new RuntimeException(e);
```
Comment (ctmay4) [inline src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:173]: According to Sonarqube and other places, it is bad practice to throw a generic exception.

https://rules.sonarsource.com/java/RSPEC-112/

Maybe a new exception should be created? `GeocodioReadException` which derives from `RuntimeException`.

Comment (deansg) [reply src/main/java/io/github/deansg/jeocodio/GeocodioClient.java]: Replaced with UncheckedIOException, I think it's the most appropriate for this case

File: src/main/java/io/github/deansg/jeocodio/GeocodioClient.java [hunk 3]
```diff
@@ -132,28 +158,62 @@ private String formatFieldsParam(List<String> fields) {
...
+    }
+
+    private InputStream getResponseInputStream(HttpResponse<InputStream> resp) throws IOException {
+        var inputStream = resp.body();
+        if (resp.headers().firstValue("Content-Encoding").orElse("").equals("gzip")) {
+            try {
+                inputStream = new GZIPInputStream(inputStream);
+            } catch (IOException e) {
+                inputStream.close();
+                throw e;
```
Comment (ctmay4) [inline src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:185]: With the outer try-with, I don't think this is necessary, but I suppose it doesn't hurt.

**Comment by ctmay4** [comment]
This is looking good now.

**Review by ctmay4 — APPROVED** [review]

File: src/main/java/io/github/deansg/jeocodio/GeocodioClient.java (hunk 3 above)
Comment (deansg) [reply src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:185]: I actually added this because of your first comment, so that in case of an exception during the creation itself we won't have a memory leak. If you don't think this try-catch is necessary I'm not really sure what was your concern in the first comment (GZip stream definitely will close the underlying stream in a "happy" flow)

Comment (ctmay4) [reply src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:185]: And actually, if there was an exception, the stream might not be open and the `inputStream.close()` might throw an exception. The more I think about it the more I would remove this explicit close and rely on the outer try-with-resources.

Comment (ctmay4) [reply src/main/java/io/github/deansg/jeocodio/GeocodioClient.java:185]: Yeah, that way my bad. I didn't notice the outer try-with. I think this can be removed. All looks good from my end.
